require('dotenv').config();

const { Pool } = require('pg');

if (!process.env.DATABASE_URL) {
  console.error('DATABASE_URL is required.');
  process.exit(1);
}

const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
  ssl: { rejectUnauthorized: false }
});

async function applyMigration() {
  try {
    await pool.query(`
      CREATE TABLE IF NOT EXISTS password_reset_requests (
        request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id BIGINT NOT NULL REFERENCES users(user_id),
        status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'resolved')),
        requested_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        resolved_at TIMESTAMPTZ,
        resolved_by_user_id BIGINT REFERENCES users(user_id)
      )
    `);
    await pool.query(`
      CREATE UNIQUE INDEX IF NOT EXISTS one_pending_password_reset_per_user
      ON password_reset_requests (user_id)
      WHERE status = 'pending'
    `);
    console.log('Migration applied: password_reset_requests is ready.');
  } finally {
    await pool.end();
  }
}

applyMigration().catch((error) => {
  console.error('Password reset request migration failed:', error.message);
  process.exit(1);
});
