-- Run once against existing deployments.
CREATE TABLE IF NOT EXISTS password_reset_requests (
  request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(user_id),
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'resolved')),
  requested_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  resolved_at TIMESTAMPTZ,
  resolved_by_user_id BIGINT REFERENCES users(user_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS one_pending_password_reset_per_user
  ON password_reset_requests (user_id)
  WHERE status = 'pending';
