import React, { useCallback, useEffect, useState } from 'react';
import { Plus, UserX } from 'lucide-react';
import DeactivateAccountModal from '../components/DeactivateAccountModal';
import CreateStaffAccountModal from '../components/CreateStaffAccountModal';
import { authFetch } from '../api/authFetch';

const UsersPage = () => {
  const [users, setUsers] = useState([]); const [selected, setSelected] = useState(null); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [createOpen, setCreateOpen] = useState(false); const [savingRoleId, setSavingRoleId] = useState(null);
  const loadUsers = useCallback(async () => { const r = await authFetch('/users'); const d = await r.json(); if (!r.ok) throw new Error(d.message || 'Unable to load users.'); setUsers(d); }, []);
  useEffect(() => { const timer = window.setTimeout(() => { loadUsers().catch((e) => setMessage(e.message)); }, 0); return () => window.clearTimeout(timer); }, [loadUsers]);
  const deactivate = async (payload) => { try { const r = await authFetch(`/users/${selected.user_id}`, { method: 'DELETE', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); const d = await r.json(); if (r.status === 409 && d.requiresOverride) return d; if (!r.ok) return { error: d.message || 'Unable to deactivate account.' }; setSelected(null); setMessage(`${selected.name}'s account was deactivated.`); await loadUsers(); return {}; } catch (e) { return { error: e.message }; } };
  const createStaff = async (form) => { try { const r = await authFetch('/users', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); const d = await r.json(); if (!r.ok) return { error: d.message || 'Unable to create account.' }; setCreateOpen(false); setMessage(`${d.user.name}'s staff account was created.`); await loadUsers(); return {}; } catch (e) { return { error: e.message }; } };
  const changeRole = async (user, role) => { setSavingRoleId(user.user_id); setError(''); try { const r = await authFetch(`/users/${user.user_id}/role`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ role }) }); const d = await r.json(); if (!r.ok) throw new Error(d.message || 'Unable to update role.'); setMessage(`${user.name}'s role is now ${role}.`); await loadUsers(); } catch (e) { setError(e.message); await loadUsers(); } finally { setSavingRoleId(null); } };
  return <div className="page-container"><div className="page-header"><div><h1 className="page-title">User management</h1><p className="page-subtitle">Create staff accounts, manage roles, and deactivate access while retaining clinical history.</p></div><button className="btn btn-primary" onClick={() => { setError(''); setCreateOpen(true); }}><Plus size={18} /> Create Staff Account</button></div>{message && <div className="alert alert-success">{message}</div>}{error && <div className="alert alert-error">{error}</div>}<div className="section-card"><div className="table-container"><table className="table"><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Status</th><th>Action</th></tr></thead><tbody>{users.map((u) => <tr key={u.user_id}><td><strong>{u.name}</strong></td><td>{u.email}</td><td><select className="form-control" value={u.role} disabled={savingRoleId === u.user_id} onChange={(event) => changeRole(u, event.target.value)} aria-label={`Change ${u.name}'s role`} style={{ minWidth: 130, textTransform: 'capitalize' }}>{['admin', 'doctor', 'nurse', 'receptionist'].map((role) => <option key={role} value={role}>{role[0].toUpperCase() + role.slice(1)}</option>)}</select></td><td><span className={`badge ${u.is_active ? 'badge-low' : 'badge-high'}`}>{u.is_active ? 'Active' : 'Deactivated'}</span></td><td>{u.is_active && <button className="btn btn-danger" style={{ padding: '6px 10px', fontSize: 12 }} onClick={() => { setMessage(''); setSelected(u); }}><UserX size={14} /> Deactivate</button>}</td></tr>)}{!users.length && <tr><td colSpan="5" className="text-center">No users found.</td></tr>}</tbody></table></div></div>{selected && <DeactivateAccountModal user={selected} onClose={() => setSelected(null)} onConfirm={deactivate} />}{createOpen && <CreateStaffAccountModal onClose={() => setCreateOpen(false)} onCreate={createStaff} />}</div>;
};
export default UsersPage;
